# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^(cmake/ECM|cmake/CodeCoverage.cmake|cmake/CheckAtomic.cmake|tests/doctest/doctest.h|assets/fonts/Roboto|.cmake-format.py)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: (.svg)
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
  - id: clang-format
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-lint
    exclude: (.yml.cmake|Doxyfile.cmake|CMakeRC.cmake)
  - id: cmake-format
    exclude: (.yml.cmake|Doxyfile.cmake|CMakeRC.cmake)
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
  - id: markdownlint
    entry: mdl
    language: ruby
    files: \.(md|mdown|markdown)$
- repo: https://github.com/fsfe/reuse-tool
  rev: v3.1.0a1
  hooks:
  - id: reuse
