#pragma once

#include <toy_renderer/gpu_core.h>

#include <vulkan/vulkan.h>

namespace ToyRenderer {

AdapterDeviceType vkPhysicalDeviceTypeToAdapterDeviceType(VkPhysicalDeviceType deviceType);

Format vkFormatToFormat(VkFormat format);
VkFormat formatToVkFormat(Format format);

ColorSpace vkColorSpaceKHRToColorSpace(VkColorSpaceKHR colorSpace);
VkColorSpaceKHR colorSpaceToVkColorSpaceKHR(ColorSpace colorSpace);

PresentMode vkPresentModeKHRToPresentMode(VkPresentModeKHR presentMode);
VkPresentModeKHR presentModeToVkPresentModeKHR(PresentMode presentMode);

SurfaceTransformFlagBits vkSurfaceTransformFlagBitsKHRToSurfaceTransformFlagBits(VkSurfaceTransformFlagBitsKHR transform);
VkSurfaceTransformFlagBitsKHR surfaceTransformFlagBitsToVkSurfaceTransformFlagBitsKHR(SurfaceTransformFlagBits transform);

CompositeAlphaFlagBits vkCompositeAlphaFlagBitsKHRToCompositeAlphaFlagBits(VkCompositeAlphaFlagBitsKHR compositeAlpha);
VkCompositeAlphaFlagBitsKHR compositeAlphaFlagBitsToVkCompositeAlphaFlagBitsKHR(CompositeAlphaFlagBits compositeAlpha);

SharingMode vkSharingModeToSharingMode(VkSharingMode sharingMode);
VkSharingMode sharingModeToVkSharingMode(SharingMode sharingMode);

ViewType vkImageViewTypeToViewType(VkImageViewType viewType);
VkImageViewType viewTypeToVkImageViewType(ViewType viewType);

} // namespace ToyRenderer
